CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE INTEGER,
AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE) VALUES
("1", "JACOB","NAIROBI", "01265" , 18),
("2", "ADAM","KISUMU", "01982" , 18),
("3", "CHOSO","NAKURU", "01873" , 20),
("4", "RAMESH","DELHI", "01973" , 18),
("5", "YUKI", "KYOTO" "01861" , 20),
("6", "OCHIENG","GARISSA" "01860" , 18);


SELECT * FROM STUDENT WHERE AGE = 20 AND (NAME = "CHOSO" OR NAME = "YUKI");

SELECT * FROM Salesman;

SELECT * FROM STUDENT;

SELECT * FROM WHERE AGE = 18 AND ADDRESS = "GARISSA";

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = "OCHIENG";

SELECT * FROM STUDENT WHERE NAME = "OCHIENG" OR NAME = "RAMESH";

SELECT * FROM STUDENT WHERE NAME = "OCHIENG" OR AGE = 20;
